apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "redis-exporter.fullname" . }}
  labels:
    {{- include "redis-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "redis-exporter.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    interval: 15s
