spec:
  template:
    spec:
      containers:
      - name: grafana
        volumeMounts:
        - name: grafana-config-volume
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
      volumes:
      - name: grafana-config-volume
        configMap:
          name: grafana-config
